esphome:
  name: realdash
external_components:
  - source: github://creepystefan/realdash-esphome
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 
    
logger:
  baud_rate: 0
  
ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
captive_portal:

realdash:
  - platform: frame44
    canid: 1           
    data1:              
    data2:
    data3:
    data4:
    
  
sensor:
  - platform: ....
    id:              # data1 or data2 or data3 or data4 
  
