external_components:
  - source: github://creepystefan/realdash-esphome
  #- source: my_components

esphome:
  name: realdash


esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3 

logger:
  baud_rate: 115200
  level: DEBUG
    

uart:
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: true

ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet


captive_portal:

realdash:
  canid: 44
  data1: 1
  data2: 2
  data3: 3
  data4: 4
  sensors:
    - id: sens1
      name: sens1
    - id: sens3
      name: sens3
    - id: sens2
      name: sens2

sensor:
  - platform: template
    name: sens1
    id: sens1
    update_interval: 1s
    lambda: |-
       return 200;

  - platform: template
    name: sens2
    id: sens2
    update_interval: 1s
    lambda: |-
       return 40;

  - platform: template
    name: sens3
    id: sens3
    update_interval: 1s
    lambda: |-
       return 50;

